DROP TABLE "APP"."SCENE_TELEPORTER";

CREATE TABLE "APP"."SCENE_TELEPORTER" (
		"ID" NUMERIC(8 , 0) NOT NULL,
		"START_ID" NUMERIC(8 , 0) NOT NULL,
		"END_ID" NUMERIC(8 , 0) NOT NULL,
		"START_POINT" VARCHAR(8) NOT NULL,
		"END_POINT" VARCHAR(8) NOT NULL,
		"DESCRIPTION" VARCHAR(200)
	);

CREATE INDEX "APP"."SCENE_TELEPORTER_END_ID_IDX" ON "APP"."SCENE_TELEPORTER" ("END_ID");

CREATE INDEX "APP"."SCENE_TELEPORTER_START_ID_IDX" ON "APP"."SCENE_TELEPORTER" ("START_ID");

CREATE UNIQUE INDEX "APP"."SQL100418120731600" ON "APP"."SCENE_TELEPORTER" ("ID");

ALTER TABLE "APP"."SCENE_TELEPORTER" ADD CONSTRAINT "SQL100418120731600" PRIMARY KEY ("ID");

