DROP TABLE "APP"."SCENE_NPC";

CREATE TABLE "APP"."SCENE_NPC" (
		"ID" NUMERIC(8 , 0) NOT NULL,
		"SCENE_ID" NUMERIC(8 , 0) NOT NULL,
		"CHARACTER_ID" VARCHAR(20) NOT NULL,
		"NAME" VARCHAR(30) NOT NULL,
		"SCENE_X" NUMERIC(8 , 0) NOT NULL,
		"SCENE_Y" NUMERIC(8 , 0) NOT NULL,
		"CONFIG" VARCHAR(2000) NOT NULL,
		"DESCRIPTION" VARCHAR(400)
	);

CREATE INDEX "APP"."SCENE_NPC_NAME_IDX" ON "APP"."SCENE_NPC" ("NAME");

CREATE INDEX "APP"."SCENE_NPC_SCENE_ID_IDX" ON "APP"."SCENE_NPC" ("SCENE_ID");

CREATE UNIQUE INDEX "APP"."SQL100418140421570" ON "APP"."SCENE_NPC" ("ID", "SCENE_ID");

ALTER TABLE "APP"."SCENE_NPC" ADD CONSTRAINT "SQL100418140421570" PRIMARY KEY ("ID");

