DROP TABLE "APP"."ITEM_WEAPON";

CREATE TABLE "APP"."ITEM_WEAPON" (
		"ID" NUMERIC(10 , 0) NOT NULL,
		"RES_NO" VARCHAR(20) ,
		"LEVEL" NUMERIC(4 , 0) DEFAULT 0 NOT NULL,
		"NAME" VARCHAR(20) NOT NULL,
		"DESCRIPTION" VARCHAR(400),
        "CHARACTER" VARCHAR(60),
		"PRICE" NUMERIC(10 , 0) DEFAULT 0 NOT NULL,
		"ADD_ATTRIBUTE1" NUMERIC(10 , 0),
        "ADD_ATTRIBUTE2" NUMERIC(10 , 0),	
        "ACCURACY" NUMERIC(10 , 0), 
		"DAMAGE" NUMERIC(10 , 0),
        "DODGE" NUMERIC(10 , 0),
		"TYPE" VARCHAR(10) NOT NULL,
        "ADD_SKILL" VARCHAR(50),
		"EFFICACY" VARCHAR(20)
	);

CREATE INDEX "APP"."ITEM_WEAPON_IDX" ON "APP"."ITEM_WEAPON" ("TYPE");

CREATE UNIQUE INDEX "APP"."ITEM_WEAPON_NAME" ON "APP"."ITEM_WEAPON" ("NAME");

CREATE UNIQUE INDEX "APP"."SQL100417191125325" ON "APP"."ITEM_WEAPON" ("ID");

ALTER TABLE "APP"."ITEM_WEAPON" ADD CONSTRAINT "SQL100417191125325" PRIMARY KEY ("ID");

